server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8090/postgres
    username: postgres
    password: pass1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

sonar:
  projectKey: ClientProject
  projectName: ClientProject
  host:
    url: http://localhost:9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
